kind: Service
apiVersion: v1
metadata:
  name: iis-vm
  namespace: demo-vm-ossm
spec:
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: identity
      protocol: TCP
      port: 8081
      targetPort: 8081
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    vm.kubevirt.io/name: win2k22-iis