apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: windows-efi-installer
  namespace: openshift-virtualization-os-images
spec:
  description: This pipeline installs Windows 11/2k22 into a new DataVolume. Then the  DataVolume is suitable to be used as a default boot source or golden image  for Windows 11/2k22 VMs. Different OS versions requires different  customizeConfigMapName parameter with unattend.xml.
  finally:
    - name: cleanup-vm
      params:
        - name: vmName
          value: $(tasks.create-vm.results.name)
        - name: vmNamespace
          value: $(tasks.create-vm.results.namespace)
        - name: delete
          value: 'true'
      taskRef:
        kind: Task
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: cleanup-vm
          - name: version
            value: v0.19.0
        resolver: hub
      timeout: 10m0s
    - name: delete-imported-iso
      params:
        - name: deleteObject
          value: 'true'
        - name: deleteObjectKind
          value: DataVolume
        - name: deleteObjectName
          value: $(tasks.import-win-iso.results.name)
        - name: namespace
          value: $(tasks.import-win-iso.results.namespace)
      taskRef:
        kind: Task
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-data-object
          - name: version
            value: v0.19.0
        resolver: hub
    - name: delete-vm-rootdisk
      params:
        - name: deleteObject
          value: 'true'
        - name: deleteObjectKind
          value: DataVolume
        - name: deleteObjectName
          value: $(tasks.create-vm-root-disk.results.name)
        - name: namespace
          value: $(tasks.create-vm-root-disk.results.namespace)
      taskRef:
        kind: Task
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-data-object
          - name: version
            value: v0.19.0
        resolver: hub
  params:
    - description: 'Download URL to Windows 11 or server 2022 installation ISO (English United States x64 version is needed). You can follow https://www.microsoft.com/en-us/software-download/windows11 or https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2022 to get one.'
      name: winImageDownloadURL
      type: string
    - default: u1.large
      description: Name of VirtualMachineClusterInstancetype object
      name: instanceTypeName
      type: string
    - default: VirtualMachineClusterInstancetype
      description: Kind of VirtualMachineInstancetype object
      name: instanceTypeKind
      type: string
    - default: windows.11
      description: Name of VirtualMachineClusterPreference object
      name: preferenceName
      type: string
    - default: VirtualMachineClusterPreference
      description: Kind of virtualMachinePreference object
      name: virtualMachinePreferenceKind
      type: string
    - default: windows11-autounattend
      description: 'Name of the ConfigMap containing the sysprep configuration files (autounattend.xml, etc.). For example windows11-autounattend or windows2022-autounattend. It is possible to provide customize ConfigMaps created by the user too.'
      name: autounattendConfigMapName
      type: string
    - default: 'quay.io/kubevirt/virtio-container-disk:v1.2.0'
      description: Reference to the containerdisk containing the virtio-win drivers ISO.
      name: virtioContainerDiskName
      type: string
    - default: win11
      description: Name of the base DataVolume which is created. Pre-installed Windows VMs can be created from this DataVolume.
      name: baseDvName
      type: string
    - default: openshift-virtualization-os-images
      description: Namespace of the base DataVolume which is created.
      name: baseDvNamespace
      type: string
    - default: win11
      description: Name of Windows ISO datavolume
      name: isoDVName
      type: string
  results:
    - description: Name of the created base DataVolume
      name: baseDvName
      value: $(tasks.create-base-dv.results.name)
    - description: Namespace of the created base DataVolume
      name: baseDvNamespace
      value: $(tasks.create-base-dv.results.namespace)
  tasks:
    - name: import-win-iso
      params:
        - name: manifest
          value: |-
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              generateName: $(params.isoDVName)-
            spec:
              source:
                http:
                  url: $(params.winImageDownloadURL)
              storage:
                volumeMode: Filesystem
                resources:
                  requests:
                    storage: 9Gi
        - name: waitForSuccess
          value: 'false'
        - name: allowReplace
          value: 'true'
      taskRef:
        kind: Task
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-data-object
          - name: version
            value: v0.19.0
        resolver: hub
    - name: modify-windows-iso-file
      params:
        - name: pvcName
          value: $(tasks.import-win-iso.results.name)
      runAfter:
        - import-win-iso
        - create-vm-root-disk
      taskRef:
        kind: Task
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-windows-iso-file
          - name: version
            value: v0.19.0
        resolver: hub
    - name: create-vm-root-disk
      params:
        - name: manifest
          value: |-
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              generateName: windows-efi-root-disk-
            spec:
              storage:
                resources:
                  requests:
                    storage: 20Gi
              source:
                blank: {}
        - name: waitForSuccess
          value: 'false'
      taskRef:
        kind: Task
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-data-object
          - name: version
            value: v0.19.0
        resolver: hub
    - name: create-vm
      params:
        - name: runStrategy
          value: RerunOnFailure
        - name: manifest
          value: |-
            apiVersion: kubevirt.io/v1
            kind: VirtualMachine
            metadata:
              generateName: windows-efi-
            spec:
              instancetype:
                kind: $(params.instanceTypeKind)
                name: $(params.instanceTypeName)
              preference:
                kind: $(params.virtualMachinePreferenceKind)
                name: $(params.preferenceName)
              template:
                spec:
                  evictionStrategy: LiveMigrateIfPossible
                  domain:
                    devices:
                      disks:
                        - cdrom:
                            bus: sata
                          name: installcdrom
                          bootOrder: 2
                        - disk:
                            bus: virtio
                          name: rootdisk
                          bootOrder: 1
                        - cdrom:
                            bus: sata
                          name: virtiocontainerdisk
                        - cdrom:
                            bus: sata
                          name: sysprep
                  volumes:
                  - name: installcdrom
                    persistentVolumeClaim:
                      claimName: $(tasks.import-win-iso.results.name)
                  - name: virtiocontainerdisk
                    containerDisk:
                      image: $(params.virtioContainerDiskName)
                  - name: sysprep
                    sysprep:
                      configMap: 
                        name: $(params.autounattendConfigMapName)
                  - dataVolume:
                      name:  $(tasks.create-vm-root-disk.results.name)
                    name: rootdisk
      runAfter:
        - modify-windows-iso-file
      taskRef:
        kind: Task
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: create-vm-from-manifest
          - name: version
            value: v0.19.0
        resolver: hub
    - name: wait-for-vmi-status
      params:
        - name: vmiName
          value: $(tasks.create-vm.results.name)
        - name: vmiNamespace
          value: $(tasks.create-vm.results.namespace)
        - name: successCondition
          value: status.phase == Succeeded
        - name: failureCondition
          value: 'status.phase in (Failed, Unknown)'
      runAfter:
        - create-vm
      taskRef:
        kind: Task
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: wait-for-vmi-status
          - name: version
            value: v0.19.0
        resolver: hub
      timeout: 2h0m0s
    - name: create-base-dv
      params:
        - name: manifest
          value: |
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              annotations:
                "cdi.kubevirt.io/storage.bind.immediate.requested": "true"
              labels:
                "instancetype.kubevirt.io/default-instancetype-kind": $(params.instanceTypeKind)
                "instancetype.kubevirt.io/default-instancetype": $(params.instanceTypeName)
                "instancetype.kubevirt.io/default-preference-kind": $(params.virtualMachinePreferenceKind)
                "instancetype.kubevirt.io/default-preference": $(params.preferenceName)
              name: $(params.baseDvName)
              namespace: $(params.baseDvNamespace)
            spec:
              storage: {}
              source:
                pvc:
                  name: $(tasks.create-vm-root-disk.results.name)
                  namespace: $(tasks.create-vm-root-disk.results.namespace)
        - name: waitForSuccess
          value: 'true'
        - name: allowReplace
          value: 'true'
      runAfter:
        - wait-for-vmi-status
      taskRef:
        kind: Task
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-data-object
          - name: version
            value: v0.19.0
        resolver: hub
