kind: Service
apiVersion: v1
metadata:
  name: ${{values.name}}
  namespace: ${{values.namespace}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    vm.kubevirt.io/name: ${{values.name}}-vm