kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${{ values.name }}-puller
  namespace: build-dotnet
subjects:
  - kind: ServiceAccount
    name: default
    namespace: test-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
