apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: iis-frontend
  title: IIS Frontend Application
  description: Create a container that will deploy an IIS application from container image
spec:
  owner: backstage/techdocs-core
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: What is the existing system
      required:
        - system
        - backend
      properties:
        system:
          title: Name
          type: string
          description: Existing system to add the VM to
          ui:autofocus: true
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: System
        backend:
          title: Backend
          type: string
          description: Existing backend to call from frontend
          ui:autofocus: true
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Component
    - title: IIS Deployment Options
      required:
        - container
        - name
      properties:
        name:
          title: Name of App
          type: string
          description: This is the name of the application
          ui:autofocus: true
          default: "web"
        container:
          title: Container Image
          type: string
          description: The location for the container app
          default: image-registry.openshift-image-registry.svc:5000/build-dotnet/solacetk-ui:latest


  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: systemFetch
      name: Fetch System Entity
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.system }}
    - id: backendFetch
      name: Fetch Backend Entity
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.backend }}
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          backendServiceName: ${{ steps.backendFetch.output.entity.metadata.name }}
          image: ${{ parameters.container }}
          name: ${{ parameters.name }}
          owner: ${{ user.entity.metadata.name }}
          host: ${{ steps.systemFetch.output.entity.metadata.annotations['gitlab.com/instance'] }}
          destination: development/${{ steps.systemFetch.output.entity.metadata.name }}
          repo_destination: https://${{ steps.systemFetch.output.entity.metadata.annotations['gitlab.com/instance'] }}/development/${{ steps.systemFetch.output.entity.metadata.name }}.git
          namespace: ${{steps.systemFetch.output.entity.metadata.name}}-dev
          appname: ${{ parameters.name }}
          zipfile: ${{ parameters.zip }}
          
    - id: debug1
      name: annotations
      action: debug:log
      input:
        message: entity fetched ${{ steps.systemFetch.output.entity.metadata.annotations | dump }}
    - id: debug2
      name: gitlab host
      action: debug:log
      input:
        message: https://${{ steps.systemFetch.output.entity.metadata.annotations['gitlab.com/instance'] }}?owner=development&repo=${{ steps.systemFetch.output.entity.metadata.name }}

    - id: publish
      name: Publish
      action: gitlab:repo:push
      input:
        repoUrl: "${{ steps.systemFetch.output.entity.metadata.annotations['gitlab.com/instance'] }}?owner=development&repo=${{ steps.systemFetch.output.entity.metadata.name }}"
        branchName: master
        commitMessage: "Add IIS app ${{ parameters.name }}"

    - id: register
      name: Register
      action: catalog:register
      input:
        catalogInfoUrl: https://${{ steps.systemFetch.output.entity.metadata.annotations['gitlab.com/instance'] }}/development/${{ steps.systemFetch.output.entity.metadata.name }}/-/blob/master/${{parameters.name}}-frontend-component.yaml
